[repo]
minVersion = "v0.0.29"
title = "Anexya's Test Package Repository"
summary = "Test repository for learning Stapler"
description = """
This repository contains test packages created for learning Stapler.
All packages are designed to demonstrate package creation process.
"""
url = "https://github.com/Anexya/stpl-test.git"
mirrors = []
report_url = "https://github.com/Anexya/stpl-test/issues?title=Package+{{ .BasePackageName }}"
homepage = "https://github.com/Anexya/stpl-test"
icon = "https://cdn-icons-png.flaticon.com/512/1041/1041426.png"
type = "git"
ref = "main"
